// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsK35kthQjj_mJouIbgrBn9uKRFsF0J1w',
    appId: '1:99263444116:web:dc4bb0905b6944a50eb081',
    messagingSenderId: '99263444116',
    projectId: 'garbage-automation-system',
    authDomain: 'garbage-automation-system.firebaseapp.com',
    storageBucket: 'garbage-automation-system.appspot.com',
    measurementId: 'G-YRZEZX6HJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZUUH-N-E-YpaTN-Rm0DOtG6U8tY59q-w',
    appId: '1:99263444116:android:dcab74a6d2fe46a60eb081',
    messagingSenderId: '99263444116',
    projectId: 'garbage-automation-system',
    storageBucket: 'garbage-automation-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1l5pHGMnGzu9Y2YveNHDxhHjyx0Wj3W4',
    appId: '1:99263444116:ios:b28413f6cc0eca850eb081',
    messagingSenderId: '99263444116',
    projectId: 'garbage-automation-system',
    storageBucket: 'garbage-automation-system.appspot.com',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1l5pHGMnGzu9Y2YveNHDxhHjyx0Wj3W4',
    appId: '1:99263444116:ios:2a27c012035f33210eb081',
    messagingSenderId: '99263444116',
    projectId: 'garbage-automation-system',
    storageBucket: 'garbage-automation-system.appspot.com',
    iosBundleId: 'com.example.flutterApplication4.RunnerTests',
  );
}
